name: 'CI go example workflow'
on:
  pull_request:
    branches:
      - develop
jobs:
  check-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.15', '1.16']
    name: Go ${{matrix.go}} sample
    steps:
      - name: checkout project
        uses: actions/checkout@v2
      - name: setup go environment
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}
      - name: run tests
        run: go test
      - name: run app
        run: go run math.go
